# Generated by Django 5.0 on 2023-12-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing360', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='input_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date')], default='text', max_length=10),
        ),
    ]
