# Generated by Django 5.0 on 2023-12-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing360', '0002_feature_input_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='choices',
            field=models.TextField(blank=True, help_text='Enter radio options separated by commas'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='input_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('checkbox', 'Checkbox'), ('radio', 'Radio')], default='text', max_length=10),
        ),
    ]
