# Generated by Django 5.0 on 2023-12-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing360', '0003_feature_choices_alter_feature_input_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='default_value',
            field=models.CharField(blank=True, help_text='Default value for the feature', max_length=255),
        ),
    ]
