# Generated by Django 5.0 on 2024-01-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing360', '0007_myuser_nom_myuser_prenom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='prenom',
            field=models.CharField(max_length=100),
        ),
    ]
