# Generated by Django 5.0 on 2024-01-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing360', '0009_remove_myuser_nom_remove_myuser_prenom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(default='False', max_length=30),
        ),
        migrations.AddField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(default='False', max_length=30),
        ),
    ]
