# Generated by Django 5.0 on 2024-02-01 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('listing360', '0011_alter_myuser_first_name_alter_myuser_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyfeature',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='propertyfeature',
            name='property',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
        migrations.CreateModel(
            name='DateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('field_type', models.CharField(blank=True, editable=False, max_length=100)),
                ('required', models.BooleanField(default=False)),
                ('minDate', models.DateField(blank=True, null=True)),
                ('maxDate', models.DateField(blank=True, null=True)),
                ('categories', models.ManyToManyField(to='listing360.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntegerField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('field_type', models.CharField(blank=True, editable=False, max_length=100)),
                ('required', models.BooleanField(default=False)),
                ('minValue', models.IntegerField(blank=True, null=True)),
                ('maxValue', models.IntegerField(blank=True, null=True)),
                ('categories', models.ManyToManyField(to='listing360.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LongTextField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('field_type', models.CharField(blank=True, editable=False, max_length=100)),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('rows', models.PositiveIntegerField(default=4)),
                ('cols', models.PositiveIntegerField(default=50)),
                ('maxLength', models.PositiveIntegerField(blank=True, null=True)),
                ('required', models.BooleanField(default=False)),
                ('spellCheck', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(to='listing360.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('value', models.TextField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_values', to='listing360.property')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='listing360.property')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='listing360.property')),
            ],
        ),
        migrations.CreateModel(
            name='SelectField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('field_type', models.CharField(blank=True, editable=False, max_length=100)),
                ('required', models.BooleanField(default=False)),
                ('defaultValue', models.CharField(blank=True, max_length=255, null=True)),
                ('categories', models.ManyToManyField(to='listing360.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SelectOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_value', models.CharField(max_length=100)),
                ('option_label', models.CharField(max_length=100)),
                ('select_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='listing360.selectfield')),
            ],
        ),
        migrations.CreateModel(
            name='SelectFieldDefaultValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='listing360.selectfield')),
                ('default_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listing360.selectoption')),
            ],
        ),
        migrations.CreateModel(
            name='ShortTextField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('field_type', models.CharField(blank=True, editable=False, max_length=100)),
                ('max_length', models.PositiveIntegerField(default=255)),
                ('required', models.BooleanField(default=False)),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('regex_pattern', models.CharField(blank=True, max_length=255, null=True)),
                ('categories', models.ManyToManyField(to='listing360.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CategoryFeature',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='PropertyFeature',
        ),
    ]
