# Generated by Django 5.0 on 2024-02-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing360', '0012_remove_propertyfeature_feature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='application_type',
            field=models.CharField(choices=[('sale', 'Vente'), ('rent', 'Location'), ('both', 'Les deux')], default='both', max_length=10),
        ),
    ]
