# Generated by Django 5.0 on 2024-02-09 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('listing360', '0015_alter_property_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datefield',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='datefield',
            name='required',
        ),
        migrations.RemoveField(
            model_name='integerfield',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='integerfield',
            name='required',
        ),
        migrations.RemoveField(
            model_name='longtextfield',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='longtextfield',
            name='required',
        ),
        migrations.RemoveField(
            model_name='selectfield',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='selectfield',
            name='required',
        ),
        migrations.RemoveField(
            model_name='shorttextfield',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='shorttextfield',
            name='required',
        ),
        migrations.CreateModel(
            name='CategoryField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_fields', to='listing360.category')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('longtextfield', 'datefield', 'integerfield', 'selectfield', 'shorttextfield')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
