# Generated by Django 5.0 on 2024-02-12 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing360', '0016_remove_datefield_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('field_type', models.CharField(blank=True, editable=False, max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='categoryfield',
            options={},
        ),
        migrations.RemoveField(
            model_name='datefield',
            name='field_name',
        ),
        migrations.RemoveField(
            model_name='datefield',
            name='field_type',
        ),
        migrations.RemoveField(
            model_name='datefield',
            name='label',
        ),
        migrations.RemoveField(
            model_name='integerfield',
            name='field_name',
        ),
        migrations.RemoveField(
            model_name='integerfield',
            name='field_type',
        ),
        migrations.RemoveField(
            model_name='integerfield',
            name='label',
        ),
        migrations.RemoveField(
            model_name='longtextfield',
            name='field_name',
        ),
        migrations.RemoveField(
            model_name='longtextfield',
            name='field_type',
        ),
        migrations.RemoveField(
            model_name='longtextfield',
            name='label',
        ),
        migrations.RemoveField(
            model_name='selectfield',
            name='field_name',
        ),
        migrations.RemoveField(
            model_name='selectfield',
            name='field_type',
        ),
        migrations.RemoveField(
            model_name='selectfield',
            name='label',
        ),
        migrations.RemoveField(
            model_name='shorttextfield',
            name='field_name',
        ),
        migrations.RemoveField(
            model_name='shorttextfield',
            name='field_type',
        ),
        migrations.RemoveField(
            model_name='shorttextfield',
            name='label',
        ),
        migrations.AddField(
            model_name='categoryfield',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_fields', to='listing360.field'),
        ),
        migrations.AddField(
            model_name='datefield',
            name='base_field',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='datefield', to='listing360.field'),
        ),
        migrations.AddField(
            model_name='integerfield',
            name='base_field',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='integerfield', to='listing360.field'),
        ),
        migrations.AddField(
            model_name='longtextfield',
            name='base_field',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='longtext', to='listing360.field'),
        ),
        migrations.AddField(
            model_name='selectfield',
            name='base_field',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='selectfield', to='listing360.field'),
        ),
        migrations.AddField(
            model_name='shorttextfield',
            name='base_field',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shorttextfield', to='listing360.field'),
        ),
        migrations.AlterUniqueTogether(
            name='categoryfield',
            unique_together={('category', 'field')},
        ),
        migrations.RemoveField(
            model_name='categoryfield',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='categoryfield',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='categoryfield',
            name='order',
        ),
    ]
