# Generated by Django 5.0 on 2024-02-12 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing360', '0017_field_alter_categoryfield_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryfield',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_fields', to='listing360.field'),
        ),
        migrations.AlterField(
            model_name='datefield',
            name='base_field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datefield', to='listing360.field'),
        ),
        migrations.AlterField(
            model_name='integerfield',
            name='base_field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integerfield', to='listing360.field'),
        ),
        migrations.AlterField(
            model_name='longtextfield',
            name='base_field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='longtext', to='listing360.field'),
        ),
        migrations.AlterField(
            model_name='selectfield',
            name='base_field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selectfield', to='listing360.field'),
        ),
        migrations.AlterField(
            model_name='shorttextfield',
            name='base_field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shorttextfield', to='listing360.field'),
        ),
    ]
