# Generated by Django 5.0 on 2024-02-20 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing360', '0018_alter_categoryfield_field_alter_datefield_base_field_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selectoption',
            old_name='option_label',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='selectoption',
            old_name='option_value',
            new_name='value',
        ),
    ]
